# Generated by Django 4.0.6 on 2022-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterField(
            model_name='client',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
